//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayForAnswer.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayForAnswer.App_GlobalResources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BtmSubmit {
            get {
                return ResourceManager.GetString("BtmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new subject.
        /// </summary>
        public static string BtnAddNewSubject {
            get {
                return ResourceManager.GetString("BtnAddNewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Password Reset.
        /// </summary>
        public static string BtnRequestPwdReset {
            get {
                return ResourceManager.GetString("BtnRequestPwdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateQuestionViewBrowswerTitle {
            get {
                return ResourceManager.GetString("CreateQuestionViewBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string CreateQuestionViewTitle {
            get {
                return ResourceManager.GetString("CreateQuestionViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more answers accepted!.
        /// </summary>
        public static string DetailQuestionViewAcceptedAnswerLbl {
            get {
                return ResourceManager.GetString("DetailQuestionViewAcceptedAnswerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Answer Editor.
        /// </summary>
        public static string DetailQuestionViewAnswerLabel {
            get {
                return ResourceManager.GetString("DetailQuestionViewAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailQuestionViewBrowswerTitle {
            get {
                return ResourceManager.GetString("DetailQuestionViewBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Answer.
        /// </summary>
        public static string DetailQuestionViewBtnPost {
            get {
                return ResourceManager.GetString("DetailQuestionViewBtnPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string DetailQuestionViewLblAccept {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer(s).
        /// </summary>
        public static string DetailQuestionViewLblAnswers {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer posted on .
        /// </summary>
        public static string DetailQuestionViewLblAnswersPosted {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblAnswersPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by user.
        /// </summary>
        public static string DetailQuestionViewLblByUser {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status:.
        /// </summary>
        public static string DetailQuestionViewLblCurrentStatus {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question posted on .
        /// </summary>
        public static string DetailQuestionViewLblQuestion {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string DetailQuestionViewLblReply {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrelated.
        /// </summary>
        public static string DetailQuestionViewLblUnrelated {
            get {
                return ResourceManager.GetString("DetailQuestionViewLblUnrelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAID - No more answers accepted!.
        /// </summary>
        public static string DetailQuestionViewPaidAnswerLbl {
            get {
                return ResourceManager.GetString("DetailQuestionViewPaidAnswerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string DetailQuestionViewSubjectLabel {
            get {
                return ResourceManager.GetString("DetailQuestionViewSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email preferences have been saved..
        /// </summary>
        public static string EmailPreferencesSuccessMsg {
            get {
                return ResourceManager.GetString("EmailPreferencesSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new email address. A confirmation email was sent to .
        /// </summary>
        public static string EmailUpdateConfirmationEmailSent {
            get {
                return ResourceManager.GetString("EmailUpdateConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email was successfully updated..
        /// </summary>
        public static string EmailUpdatedSuccessMsg {
            get {
                return ResourceManager.GetString("EmailUpdatedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when there is a change in status to a question where I posted an answer..
        /// </summary>
        public static string ENotificationsViewChkLblNotifyMyAnswersQs {
            get {
                return ResourceManager.GetString("ENotificationsViewChkLblNotifyMyAnswersQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when there is a new question related to my subjects of expertise..
        /// </summary>
        public static string ENotificationsViewChkLblNotifyMySubjects {
            get {
                return ResourceManager.GetString("ENotificationsViewChkLblNotifyMySubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when there is a reply to my question(s)..
        /// </summary>
        public static string ENotificationsViewChkLblNotifyReplyToMyQ {
            get {
                return ResourceManager.GetString("ENotificationsViewChkLblNotifyReplyToMyQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string ErrirMsgUnAndPwd {
            get {
                return ResourceManager.GetString("ErrirMsgUnAndPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided was not found..
        /// </summary>
        public static string ErrorMsgEmailAddressNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgEmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An has occurred. Please try again..
        /// </summary>
        public static string ErrorMsgException {
            get {
                return ResourceManager.GetString("ErrorMsgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string ErrorMsgPwd {
            get {
                return ResourceManager.GetString("ErrorMsgPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing your request..
        /// </summary>
        public static string ErrorViewMsg {
            get {
                return ResourceManager.GetString("ErrorViewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-confirm@payforanswer.com.
        /// </summary>
        public static string FromAutoConfirmEmailAddress {
            get {
                return ResourceManager.GetString("FromAutoConfirmEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking the button, you agree to the &lt;br /&gt;Terms of Service and Privacy Policy above..
        /// </summary>
        public static string LblAcceptTermsText {
            get {
                return ResourceManager.GetString("LblAcceptTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string LblEmailAddress {
            get {
                return ResourceManager.GetString("LblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Subjects:.
        /// </summary>
        public static string LblMySubjects {
            get {
                return ResourceManager.GetString("LblMySubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Payments.
        /// </summary>
        public static string LblPayPalPayments {
            get {
                return ResourceManager.GetString("LblPayPalPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string LblResetPassword {
            get {
                return ResourceManager.GetString("LblResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more subject(s) left to complete the registration process..
        /// </summary>
        public static string LblSubjectsLeft {
            get {
                return ResourceManager.GetString("LblSubjectsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update my email address to:.
        /// </summary>
        public static string LblUpdateEmailAddressTo {
            get {
                return ResourceManager.GetString("LblUpdateEmailAddressTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginViewBrowswerTitle {
            get {
                return ResourceManager.GetString("LoginViewBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LoginViewRegisterLink {
            get {
                return ResourceManager.GetString("LoginViewRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in..
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string MethodDiassociateLogin {
            get {
                return ResourceManager.GetString("MethodDiassociateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to {0}.  Please check your email and use the enclosed link to reset your password..
        /// </summary>
        public static string MsgAttentionPwdResetEmailSent {
            get {
                return ResourceManager.GetString("MsgAttentionPwdResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering. An email has been sent to {0}.  Please check your email and use the enclosed link to finish registration..
        /// </summary>
        public static string MsgAttentionRegEmailSent {
            get {
                return ResourceManager.GetString("MsgAttentionRegEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please report this as an issue..
        /// </summary>
        public static string MsgErrorDefault {
            get {
                return ResourceManager.GetString("MsgErrorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address field cannot be empty!.
        /// </summary>
        public static string MsgErrorEmailAddressIsEmpty {
            get {
                return ResourceManager.GetString("MsgErrorEmailAddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The password retrieval answer provided is invalid. Please check the value and try again.&quot;.
        /// </summary>
        public static string MsgErrorInvalidAnswer {
            get {
                return ResourceManager.GetString("MsgErrorInvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MsgErrorInvalidEmail {
            get {
                return ResourceManager.GetString("MsgErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string MsgErrorInvalidPassword {
            get {
                return ResourceManager.GetString("MsgErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MsgErrorInvalidQuestion {
            get {
                return ResourceManager.GetString("MsgErrorInvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MsgErrorInvalidUserName {
            get {
                return ResourceManager.GetString("MsgErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email address is the same as your current email address!.
        /// </summary>
        public static string MsgErrorNewEmailAddressEqualsCurrent {
            get {
                return ResourceManager.GetString("MsgErrorNewEmailAddressEqualsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MsgErrorProviderError {
            get {
                return ResourceManager.GetString("MsgErrorProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read your confirmation code..
        /// </summary>
        public static string MsgErrorRegComfirmationCodeMissing {
            get {
                return ResourceManager.GetString("MsgErrorRegComfirmationCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was problem while confirming your account..
        /// </summary>
        public static string MsgErrorRegistration {
            get {
                return ResourceManager.GetString("MsgErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgErrorViewBrowserTitle {
            get {
                return ResourceManager.GetString("MsgErrorViewBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string MsgErrorViewTitle {
            get {
                return ResourceManager.GetString("MsgErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur trying to update your password. Please start over by making a request to change your password, so a new email is sent to you..
        /// </summary>
        public static string MsgExceptionResetPwd {
            get {
                return ResourceManager.GetString("MsgExceptionResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string MsgInfoDuplicateEmail {
            get {
                return ResourceManager.GetString("MsgInfoDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string MsgInfoDuplicateUserName {
            get {
                return ResourceManager.GetString("MsgInfoDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to .
        /// </summary>
        public static string MsgInfoEmailSentTo {
            get {
                return ResourceManager.GetString("MsgInfoEmailSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been confirmed. Thank you!.
        /// </summary>
        public static string MsgInfoRegConfirmation {
            get {
                return ResourceManager.GetString("MsgInfoRegConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed..
        /// </summary>
        public static string MsgSuccessPwdChanged {
            get {
                return ResourceManager.GetString("MsgSuccessPwdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please report this as an issue..
        /// </summary>
        public static string MsgWarningUserRejected {
            get {
                return ResourceManager.GetString("MsgWarningUserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one tag such as (ruby-on-rails django phone), max 5 subjects.
        /// </summary>
        public static string NewQuestionSubjectPlaceHolder {
            get {
                return ResourceManager.GetString("NewQuestionSubjectPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s your question? be specific.
        /// </summary>
        public static string NewQuestionTitlePlaceHolder {
            get {
                return ResourceManager.GetString("NewQuestionTitlePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreValidation.
        /// </summary>
        public static string PreValidationViewBrowswerTitle {
            get {
                return ResourceManager.GetString("PreValidationViewBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with PayPal.
        /// </summary>
        public static string PreValidationViewBtnPay {
            get {
                return ResourceManager.GetString("PreValidationViewBtnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include responder&apos;s processing fee:.
        /// </summary>
        public static string PreValidationViewCboxRFee {
            get {
                return ResourceManager.GetString("PreValidationViewCboxRFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total: $.
        /// </summary>
        public static string PreValidationViewOrderTotal {
            get {
                return ResourceManager.GetString("PreValidationViewOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question amount:.
        /// </summary>
        public static string PreValidationViewQAmtLable {
            get {
                return ResourceManager.GetString("PreValidationViewQAmtLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee:.
        /// </summary>
        public static string PreValidationViewQFeeLable {
            get {
                return ResourceManager.GetString("PreValidationViewQFeeLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string PreValidationViewTitle {
            get {
                return ResourceManager.GetString("PreValidationViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset pwd.
        /// </summary>
        public static string RequestPwdResetViewBrowserTitle {
            get {
                return ResourceManager.GetString("RequestPwdResetViewBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Password Reset.
        /// </summary>
        public static string RequestPwdResetViewTitle {
            get {
                return ResourceManager.GetString("RequestPwdResetViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is missing a parameter or your time limit has expired to change your password. Please submit a new request..
        /// </summary>
        public static string ResetPwdTokenMissing {
            get {
                return ResourceManager.GetString("ResetPwdTokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENotifications.
        /// </summary>
        public static string SettingsENotificationBrowserTitle {
            get {
                return ResourceManager.GetString("SettingsENotificationBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notifications.
        /// </summary>
        public static string SettingsENotificationTitle {
            get {
                return ResourceManager.GetString("SettingsENotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string SettingsMyProfileBrowserTitle {
            get {
                return ResourceManager.GetString("SettingsMyProfileBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string SettingsMyProfileTitle {
            get {
                return ResourceManager.GetString("SettingsMyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments made to this address.
        /// </summary>
        public static string TxtPlaceHolderRegistrationEmail {
            get {
                return ResourceManager.GetString("TxtPlaceHolderRegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string UserProfileModelUserName {
            get {
                return ResourceManager.GetString("UserProfileModelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ViewManageBrowswerTitle {
            get {
                return ResourceManager.GetString("ViewManageBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to get paid for your accepted answers, you need an email address that is connected to an active PayPal account..
        /// </summary>
        public static string ViewRegisterPopOverPayPalText {
            get {
                return ResourceManager.GetString("ViewRegisterPopOverPayPalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Account.
        /// </summary>
        public static string ViewRegisterPopOverPayPalTitle {
            get {
                return ResourceManager.GetString("ViewRegisterPopOverPayPalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string ViewRegSubjectsBrowswerTitle {
            get {
                return ResourceManager.GetString("ViewRegSubjectsBrowswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subjects of knowledge or expertise..
        /// </summary>
        public static string ViewRegSubjectsTitle {
            get {
                return ResourceManager.GetString("ViewRegSubjectsTitle", resourceCulture);
            }
        }
    }
}
