//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayForAnswer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSubject
    {
        public long Id { get; set; }
        public long QuestionId { get; set; }
        public long SubjectId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
