//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayForAnswer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCategory
    {
        public StatusCategory()
        {
            this.Status = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Status> Status { get; set; }
    }
}
