//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayForAnswer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.QuestionSubjects = new HashSet<QuestionSubject>();
        }
    
        public long Id { get; set; }
        public string SubjectName { get; set; }
    
        public virtual ICollection<QuestionSubject> QuestionSubjects { get; set; }
    }
}
