// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class questionBeforeIncrease : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questionBeforeIncrease));
        
        string IMigrationMetadata.Id
        {
            get { return "201401252133266_questionBeforeIncrease"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
