// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PerDayMarketing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PerDayMarketing));
        
        string IMigrationMetadata.Id
        {
            get { return "201402020413437_PerDayMarketing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
