// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class marketing_new_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(marketing_new_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201401251746584_marketing_new_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
