// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CampaignManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampaignManager));
        
        string IMigrationMetadata.Id
        {
            get { return "201401202339241_CampaignManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
