// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Marketingcampaignchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marketingcampaignchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201401182019561_Marketing campaign changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
