// <auto-generated />
namespace Repository.SQL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedUsertoMarketingCampaignmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUsertoMarketingCampaignmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201401202028541_added User to MarketingCampaign model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
